### ISSUE TITLE
Issue running Android analysis

### ISSUE THREAD

**Issue by cynthiabaran** [insidersec/insider#18]
**Describe the bug**

Different errors are thrown, can't complete Android analysis. Running it in in one project I get this error

```
[INSIDER]: 2020/06/26 21:34:24 Starting analysis for Android target .
[INSIDER]: 2020/06/26 21:34:24 Starting Android source code analysis
[INSIDER]: 2020/06/26 21:34:24 Starting Android Manifest analysis
[INSIDER]: 2020/06/26 21:34:24 Loading manifest permission
[INSIDER]: 2020/06/26 21:34:24 198
[INSIDER]: 2020/06/26 21:34:24 Finished Android Manifest analysis
[INSIDER]: 2020/06/26 21:34:24 Starting Android Source Code Analysis
[INSIDER]: 2020/06/26 21:34:25 Removing: [] from file list from android tech
[INSIDER]: 2020/06/26 21:34:25 Removing: [] from file list from android tech
[INSIDER]: 2020/06/26 21:34:25 Found 4186 files to analyze.
[INSIDER]: 2020/06/26 21:34:25 loading core rules
[INSIDER]: 2020/06/26 21:34:25 Rules 8
[INSIDER]: 2020/06/26 21:34:25 loading android rules
[INSIDER]: 2020/06/26 21:34:25 Rules 8
[INSIDER]: 2020/06/26 21:34:25 Starting extracting hardcoded information
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
insider/visitor.NewInputFile(0x7ffeefbff8ff, 0x1, 0xc000478398, 0x7, 0xc0000b6000, 0x2e, 0x22e, 0x0, 0x0, 0x0, ...)
        /Users/cynthia.baran/insider/visitor/file.go:238 +0x701
insider/visitor.FindFiles.func1(0xc000478398, 0x7, 0x17dcba0, 0xc00040e820, 0x0, 0x0, 0x7, 0xc0004cacd0)
        /Users/cynthia.baran/insider/visitor/reader.go:144 +0x32b
path/filepath.walk(0xc000478398, 0x7, 0x17dcba0, 0xc00040e820, 0xc0004cae98, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:358 +0x425
path/filepath.walk(0x7ffeefbff8ff, 0x1, 0x17dcba0, 0xc0003e4000, 0xc0004cae98, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:382 +0x2ff
path/filepath.Walk(0x7ffeefbff8ff, 0x1, 0xc0004cae98, 0x1b2db60, 0xc0004caed0)
        /usr/local/go/src/path/filepath/path.go:404 +0xff
insider/visitor.FindFiles(0x7ffeefbff8ff, 0x1, 0xc00002a300, 0x162e290, 0x50, 0x49, 0x0, 0x0, 0x0)
        /Users/cynthia.baran/insider/visitor/reader.go:114 +0xbb
insider/lib.ExtractHardcodedInfo(0x7ffeefbff8ff, 0x1, 0x0, 0x0, 0x17da4c0, 0xc0000a5d40, 0xc, 0x105a)
        /Users/cynthia.baran/insider/lib/analyzer.go:309 +0x61
insider/lib.AnalyzeAndroidSource(0x7ffeefbff8ff, 0x1, 0x0, 0x0, 0xc0000a5d40, 0x15dfe1f, 0x2, 0x0, 0x0)
        /Users/cynthia.baran/insider/lib/android.go:44 +0x25c
insider/supervisors.RunAndroidSourceCodeAnalysis(0x15e01ad, 0x3, 0x7ffeefbff907, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/cynthia.baran/insider/supervisors/android.go:32 +0x2d1
main.main()
        /Users/cynthia.baran/insider/main.go:89 +0x10b2
``` 

Tried running it with a different project and I get this output
```
[INSIDER]: 2020/06/26 21:38:36 Starting analysis for Android target .
[INSIDER]: 2020/06/26 21:38:36 Starting Android source code analysis
[INSIDER]: 2020/06/26 21:38:36 Starting Android Manifest analysis
[INSIDER]: 2020/06/26 21:38:36 Loading manifest permission
[INSIDER]: 2020/06/26 21:38:36 198
[INSIDER]: 2020/06/26 21:38:37 Error: strconv.ParseBool: parsing "@bool/enable_system_alarm_service_default": invalid syntax
[INSIDER]: 2020/06/26 21:38:37 Finished analysis for Android app #.
[INSIDER]: 2020/06/26 21:38:37 strconv.ParseBool: parsing "@bool/enable_system_alarm_service_default": invalid syntax
``` 

Really don't know what's going on... Can anyone help?

**To Reproduce**
Run any android analysis

**Expected behavior**
Generate the reports

**Desktop**
 - OS: Catalina
 - Version 2.0.2

**Comment by hermescanutodesouza** [comment]
Try this ..
Insider in a root 
and the project in a folder 
Like these.

insider 
/yourproject 
 
and send me the print or log.

Thx for your help

**Comment by cynthiabaran** [comment]
That worked for the first error, thanks!

For the second project, I'm still getting the same error
```
[INSIDER]: 2020/06/26 22:16:08 Starting analysis for Android target ifood-consumer-android
[INSIDER]: 2020/06/26 22:16:08 Starting Android source code analysis
[INSIDER]: 2020/06/26 22:16:08 Starting Android Manifest analysis
[INSIDER]: 2020/06/26 22:16:08 Loading manifest permission
[INSIDER]: 2020/06/26 22:16:08 198
[INSIDER]: 2020/06/26 22:16:08 Error: strconv.ParseBool: parsing "@bool/enable_system_alarm_service_default": invalid syntax
[INSIDER]: 2020/06/26 22:16:08 Finished analysis for Android app #ifood-consumer-android
[INSIDER]: 2020/06/26 22:16:08 strconv.ParseBool: parsing "@bool/enable_system_alarm_service_default": invalid syntax
```

**Comment by cynthiabaran** [comment]
That worked for the first error, thanks!

For the second project, I'm still getting the same error
```
[INSIDER]: 2020/06/26 22:16:08 Starting analysis for Android target android-project
[INSIDER]: 2020/06/26 22:16:08 Starting Android source code analysis
[INSIDER]: 2020/06/26 22:16:08 Starting Android Manifest analysis
[INSIDER]: 2020/06/26 22:16:08 Loading manifest permission
[INSIDER]: 2020/06/26 22:16:08 198
[INSIDER]: 2020/06/26 22:16:08 Error: strconv.ParseBool: parsing "@bool/enable_system_alarm_service_default": invalid syntax
[INSIDER]: 2020/06/26 22:16:08 Finished analysis for Android app #android-project
[INSIDER]: 2020/06/26 22:16:08 strconv.ParseBool: parsing "@bool/enable_system_alarm_service_default": invalid syntax
```

**Comment by hermescanutodesouza** [comment]
Could you send me a print with your command line?
Thx

**Comment by cynthiabaran** [comment]
```
~/insider -tech android -target ~/projects/android-project/
```

**Comment by hermescanutodesouza** [comment]
Could you send your folder structure ?
Thx

**Comment by hermescanutodesouza** [comment]
Please update your projects. New updates have been made
